name: Push to master with new data

on:
  push:
    branches: [master]
    paths:
      - "public/data/gantry-locations.csv"
      - "public/data/all-rates.json"
  workflow_dispatch:

env:
  NODE_VERSION: "16"
  MAPBOX_PRIVATE_ACCESS_TOKEN: ${{ secrets.MAPBOX_PRIVATE_ACCESS_TOKEN }}
  MAPBOX_SPRITE_GANTRY_HIGHLIGHT_OUTLINE: ${{ secrets.MAPBOX_SPRITE_GANTRY_HIGHLIGHT_OUTLINE }}
  MAPBOX_SPRITE_GANTRY_OFF: ${{ secrets.MAPBOX_SPRITE_GANTRY_OFF }}
  MAPBOX_SPRITE_GANTRY_ON: ${{ secrets.MAPBOX_SPRITE_GANTRY_ON }}
  MAPBOX_SPRITE_RATE_BG: ${{ secrets.MAPBOX_SPRITE_RATE_BG }}
  MAPBOX_TILESET_ID: ${{ secrets.MAPBOX_TILESET_ID }}
  MAPBOX_TILESET_SOURCE_ID: ${{ secrets.MAPBOX_TILESET_SOURCE_ID }}
  MAPBOX_USERNAME: ${{ secrets.MAPBOX_USERNAME }}

  MAPBOX_STYLE_ID_DARK_A: ${{ secrets.MAPBOX_STYLE_ID_DARK_A }}
  MAPBOX_STYLE_ID_DARK_B: ${{ secrets.MAPBOX_STYLE_ID_DARK_B }}
  MAPBOX_STYLE_ID_LIGHT_A: ${{ secrets.MAPBOX_STYLE_ID_LIGHT_A }}
  MAPBOX_STYLE_ID_LIGHT_B: ${{ secrets.MAPBOX_STYLE_ID_LIGHT_B }}

jobs:
  generate-fonts:
    name: "Add fonts"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm run gen:fonts

  generate-tileset-source:
    name: "Update tileset source"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm run gen:tileset-source

  generate-tileset:
    name: "Create and publish tileset"
    runs-on: ubuntu-latest
    needs: generate-tileset-source
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm run gen:tileset

  generate-style-layers:
    name: "Update style layers"
    runs-on: ubuntu-latest
    needs: generate-tileset
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm run gen:styles

  generate-sprites:
    name: "Update sprites"
    runs-on: ubuntu-latest
    needs: generate-tileset
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm run gen:sprites
