name: Update ERP gantry rates

on:
  schedule:
    # https://crontab.guru/#0_0,12_*_*_*
    # Runs every day at midnight and noon
    - cron: "0 0,12 * * *"

  workflow_dispatch:

env:
  NODE_VERSION: "16"
  DATAMALL_ACCOUNT_KEY: ${{ secrets.DATAMALL_ACCOUNT_KEY }}

jobs:
  fetch-rates:
    name: "Fetch and process rates"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm ci

      - run: npm run fetch:rates

      # Update the last check date env var and trigger a new deploy
      - name: Update last check and trigger deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          npx netlify-cli env:set REACT_APP_LAST_CHECK_DATE $(npx -y ts-node -e 'console.log(Date.now())')
        # run: curl -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_HOOK_ID }}

      # Using this based on this guide:
      # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          add-paths: data
          commit-message: "chore: update rates"
          branch: "chore/update-rates"
          delete-branch: true
          branch-suffix: timestamp
          title: "chore: update rates"
          body: |
            New ERP rates have been detected!
          labels: data-update
          reviewers: sebastianquek
